### PR TITLE
Spoof network connection status if the app is in internet compat mode

### PR DESCRIPTION
**Pull request by andre4ik3**
This spoofs the active network to none to apps that don't have internet but always expect to. This fixes some broken apps (e.g. Gboard) that think the network is available but lack network permission. Apps that are aware of the runtime Internet permission and that have the permission denied will not have this applied to them, i.e. they will continue being able to see whether device is online or not even without internet permission.

This is my first time working on Android so if something is wrong please let me know.

### CODE REVIEW

**Comment by muhomorr** [comment]
What's broken in Gboard without this patch?
I've been using Gboard without the Network permission for a while, haven't noticed any issues.

**Comment by r3g-5z** [comment]
Been using Gboard without network just fine as well. The only "issue" I've noticed is emoji kitchen doesn't work but I don't know how that works so can't really say if it depends on having internet access or something.

**Comment by muhomorr** [comment]
There are more methods that apps use to detect network availability, including Gboard itself:
`registerDefaultNetworkCallback()`, `requestNetwork(), `getNetworkInfo()` etc

**Comment by thestinger** [comment]
@muhomorr They talked about it on Matrix. I think it was in #dev:grapheneos.org. They found that when it detected the network is unavailable, it would use the OS functionality for a certain feature instead of trying to use their own implementation requiring internet access. Perhaps we should implement shims for these kinds of methods to improve how apps respond to the Network toggle being disabled since it appears they don't all simply find that it doesn't work and fall back to what they would do without it being available.

**Comment by andre4ik3** [comment]
> What's broken in Gboard without this patch?

> Been using Gboard without network just fine as well.

Voice input doesn't work. Also this isn’t just for Gboard, it can be for any app that detects internet connection this way (but I only know of Gboard). Simply put, the way Gboard checks for internet is not via checking INTERNET permission, but by checking the network info (since it has read network state permission).

> There are more methods that apps use to detect network availability, including Gboard itself:
registerDefaultNetworkCallback(), requestNetwork(), getNetworkInfo() etc

You're right, I will update the pull request with those methods shortly

**Comment by andre4ik3** [comment]
Alright, I've updated it, let me know if there's anything I've missed or if something's wrong in general.

**Comment by muhomorr** [comment]
Have you tested it? I see syntax errors in the new commits.

**Comment by andre4ik3** [comment]
Sorry, I cannot test it, I only have 1 device and I need it for day-to-day use, and I can't run emulator because I don't have enough hard drive space. I am using github.dev web editor.

**Comment by muhomorr** [comment]
I think the proper way to handle this would be to revoke the `ACCESS_NETWORK_STATE` permission together with the `INTERNET` permission, and then add stubs for all APIs that are protected by `ACCESS_NETWORK_STATE`.
There are a couple of other classes that have APIs that are protected by this permission, and there are more APIs in `ConnectivityManager` too.

**Comment by andre4ik3** [comment]
That would be great however it would require more time that I currently do not have, also wouldn't it impact apps that have just `ACCESS_NETWORK_STATE` permission? It would be a good final implementation however I think this is a good starting point.

**Comment by muhomorr** [comment]
Implemented in a different way in https://github.com/GrapheneOS/platform_packages_modules_Connectivity/pull/15

Decided against revoking the `ACCESS_NETWORK_STATE` permission, at least for now. It'd be complex to migrate already installed apps to this approach.

**Pull request closed without merging**
